/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ecc;

import org.junit.Test;
import static org.junit.Assert.*;

public class ECCTest {
    @Test public void makeAPairAndPrint() {
		Pair <Integer, Integer> P = new Pair(1, 2);
        assertEquals(P.toString(), "( 1 , 2 )");
		System.out.println("TESTING !!!");
    	ECC E22 = new ECC(new Pair(2,2), new Pair(5,1), 19);
      E22.myprivates = 8;
      E22.bG = new Pair(16, 4);
	  E22.genKey("Hyrule");
	  assertEquals(E22.myPow(3,3), 10);
	  assertEquals(E22.myPow(1,1), 1);
	  assertEquals(E22.myPow(5,2), 8);
	  assertEquals(E22.myPow(2,3), 8);
	  assertEquals(E22.myPow(5,15), 7);
	  assertEquals(E22.myPow(-5,15), -7);
    assertEquals((E22.pvtkey).equals(new Pair(7, 6)), true);
	  System.out.println("pout PAST KEY GEN");
      assertEquals(E22.Encode("Hibiscus"), "Collusion");
      assertEquals((E22.pvtkey).equals(new Pair(7, 6)), true);
      assertEquals(E22.Decode("Collusion"), "Hibiscus");
      assertEquals(E22.TimesN(19, new Pair(5,1)).equals(new Pair(0,0)), true);
      assertEquals(E22.Times(new Pair(5,1), new Pair(9,16)).equals(new Pair(16, 13)), true);
      assertEquals(E22.TimesN(19, new Pair(5,16)).equals(new Pair(0,0)), true);
      assertEquals(E22.Times(new Pair(5, 16), new Pair(0, 0)).equals(new Pair (5, 16)), true);
      assertEquals(E22.Times(new Pair(0, 0), new Pair(5, 16)).equals(new Pair (5, 16)), true);
      assertEquals(E22.Times(new Pair(0, 0), new Pair(0, 0)).equals(new Pair (0, 0)), true);
    }
}
